apiVersion: v1
kind: ConfigMap
metadata:
  namespace: postgres
  name: postgres-credentials
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  # Note: For production, use Kubernetes Secrets instead of ConfigMap for passwords
  POSTGRES_PASSWORD: ps_password
  