apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

# kubectl port-forward service/postgres-service 5432:5432 -n postgres // To connect to the database from local machine